Algoritmo "IDADE"


Var

  nome1 , nome2 : caracter
  idade1, idade2 : inteiro
  media : real
 
Inicio

      escreva("Digite o nome: ")
      leia(nome1)
      escreva("Digite a idade: ")
      leia(idade1)
      escreva("Digite o nome: ")
      leia(nome2)
      escreva("Digite a idade: ")
      leia(idade2)
      

       media <- (idade1 + idade2)/2)
       
       escreval("")
        escreval("A idade media de ", nome1, " e ", nome2,  " é", media)



Fimalgoritmo