Algoritmo "Soma_impares"
// Leia 2 valores inteiros X e Y (em qualquer ordem). A seguir, calcule e mostre a soma dos números
//impares entre eles.


Var

   n , i , produto : inteiro

Inicio

      escreval("Deseja a tabuada para qual valor? ")
      leia(n)
      
      para i de 1 ate 10 faca

        produto  <- n * i
        escreval(n , " x ", i, " = ", produto)

fimpara
      
      

Fimalgoritmo